server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/api/auth/**

            - id: doctor-service
              uri: http://doctor-service:8080
              predicates:
                - Path=/api/doctors/**

            - id: appointment-service
              uri: http://appoinment:8080
              predicates:
                - Path=/api/appointments/**

            - id: payment-service
              uri: http://payment-service:8080
              predicates:
                - Path=/api/payments/**



          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: false