spring.application.name=appoinment

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/appointmentdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8084

# Inter-service communication via API Gateway
doctor.service.url=http://localhost:8080/api/doctors

# Logging
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
