name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # -------- FRONTEND --------
      - name: Build Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend

      # -------- API GATEWAY --------
      - name: Build API Gateway
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway ./services/api-gateway/api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway

      # -------- AUTH SERVICE --------
      - name: Build Auth Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service ./services/auth-service/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service

      # -------- APPOINTMENT --------
      - name: Build Appointment Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/appointment ./services/appoinment
          docker push ${{ secrets.DOCKER_USERNAME }}/appointment

      # -------- DOCTOR --------
      - name: Build Doctor Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/doctor-service ./services/doctor-service/doctor-service
          docker push ${{ secrets.DOCKER_USERNAME }}/doctor-service

      # -------- PAYMENT --------
      - name: Build Payment Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service ./services/payment-service
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service