spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/authdb
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: auth-service

jwt:
  secret: 08788b9566dad0f379f4530d090c9163cc199fdf76eef8443bee827d05bee706fff39966
  expiration: 3600000

server:
  port: 8080

eureka:
  client:
    enabled: false